
spring:
  profiles:
    active: dev # 기본 활성화 프로파일을 dev로 설정 (필요에 따라 변경 가능)

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/dev_database
    username: dev_user
    password: dev_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  server:
    port: 8081
  logging:
    level:
      root: debug

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://prod-db-host:3306/prod_database
    username: prod_user
    password: prod_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  server:
    port: 8082
  logging:
    level:
      root: info